platform :ios, '6.0'
inhibit_all_warnings!

target 'VenmoSDKSample', :exclusive => true do
  pod 'Venmo-iOS-SDK', :path => '../Venmo-iOS-SDK.podspec'
  pod 'SVProgressHUD'
  pod 'UIAlertView+Blocks'
end
