platform :ios, '8.0'
inhibit_all_warnings!

target 'MiniVenmo', :exclusive => true do
  pod 'Venmo-iOS-SDK', :path => '..'
  pod 'SVProgressHUD', '~> 1.0'
  pod 'UIAlertView+Blocks', '~> 0.8'
  pod 'AFNetworking', '~> 2.3'
end
