#import "Specta.h"
#import "VENRequestDecoder.h"

SpecBegin(VENRequestDecoder)

describe(@"decodeSignedRequest", ^{
    it(@"should decode signed request successfully", ^{
        NSString *signedRequest = @"nlVsR906913qDhrAJVj6TcdpAHvyUDDNYBbZSPm5wio.W3sic3RhdHVzIjogInNldHRsZWQiLCAicmVmdW5kIjogbnVsbCwgIm1lZGl1bSI6ICJpcGhvbmUiLCAiaWQiOiAiMTcyNDA3NzkwMDk0NjIxMTA2NyIsICJwYXltZW50X2lkIjogNzA2OTc3NjIsICJmZWUiOiBudWxsLCAiZGF0ZV9jb21wbGV0ZWQiOiAiMjAxNS0wNy0wN1QxODozNTowMSIsICJ0YXJnZXQiOiB7InBob25lIjogbnVsbCwgInR5cGUiOiAidXNlciIsICJlbWFpbCI6IG51bGwsICJ1c2VyIjogeyJ1c2VybmFtZSI6ICJiZXJpbmctdHNhbmciLCAibGFzdF9uYW1lIjogIlRzYW5nIiwgImlzX2ZyaWVuZCI6IGZhbHNlLCAiaXNfZ3JvdXAiOiBmYWxzZSwgImlzX2FjdGl2ZSI6IHRydWUsICJ0cnVzdF9yZXF1ZXN0IjogbnVsbCwgInBob25lIjogbnVsbCwgInByb2ZpbGVfcGljdHVyZV91cmwiOiAiaHR0cHM6Ly92ZW5tb3BpY3MuYXBwc3BvdC5jb20vdS92MS9mL2UyYmNkNGE4LWI2Y2YtNGJkMi1iOTExLWJlNTczMzhmMWZiMyIsICJpc19ibG9ja2VkIjogZmFsc2UsICJpZCI6ICIxMzMzNjY5Mzg1OTk0MjQwMTY3IiwgImlkZW50aXR5IjogbnVsbCwgImRhdGVfam9pbmVkIjogIjIwMTQtMDEtMTVUMDI6NDM6MDAiLCAiYWJvdXQiOiAiICIsICJkaXNwbGF5X25hbWUiOiAiQmVyaW5nIFRzYW5nIiwgImZyaWVuZHNfY291bnQiOiA0MjIsICJmaXJzdF9uYW1lIjogIkJlcmluZyIsICJmcmllbmRfcmVxdWVzdCI6IG51bGwsICJlbWFpbCI6IG51bGx9fSwgInN1Y2Nlc3MiOiAxLCAiYXVkaWVuY2UiOiAicHJpdmF0ZSIsICJhY3RvciI6IHsidXNlcm5hbWUiOiAiZWx5c3NlLWxhbmUiLCAibGFzdF9uYW1lIjogIkxhbmUiLCAiaXNfZnJpZW5kIjogZmFsc2UsICJpc19ncm91cCI6IGZhbHNlLCAiaXNfYWN0aXZlIjogdHJ1ZSwgInRydXN0X3JlcXVlc3QiOiBudWxsLCAicGhvbmUiOiBudWxsLCAicHJvZmlsZV9waWN0dXJlX3VybCI6ICJodHRwczovL3Zlbm1vcGljcy5hcHBzcG90LmNvbS91L3YxL3MvZDgwNTRkZTgtZDM1Zi00Y2RhLThjNzEtOTY4YjY4ZTcyOTJmIiwgImlzX2Jsb2NrZWQiOiBmYWxzZSwgImlkIjogIjEyMTY4MjU0ODAxODM4MDg3ODYiLCAiaWRlbnRpdHkiOiBudWxsLCAiZGF0ZV9qb2luZWQiOiAiMjAxMy0wOC0wNlQyMTozNTowMSIsICJhYm91dCI6ICJiaXRjaCBwbHoiLCAiZGlzcGxheV9uYW1lIjogIkVseXNzZSBMYW5lIiwgImZyaWVuZHNfY291bnQiOiA2MSwgImZpcnN0X25hbWUiOiAiRWx5c3NlIiwgImZyaWVuZF9yZXF1ZXN0IjogbnVsbCwgImVtYWlsIjogbnVsbH0sICJub3RlIjogIkZvciBiaWxseiBvbiBzcGxpdHdpc2UiLCAiYW1vdW50IjogIjU4LjExIiwgImFjdGlvbiI6ICJwYXkiLCAiZGF0ZV9jcmVhdGVkIjogIjIwMTUtMDctMDdUMTg6MzU6MDEiLCAiZGF0ZV9yZW1pbmRlZCI6IG51bGx9XQ";
        NSArray *decodedSignedRequest = [VENRequestDecoder decodeSignedRequest:signedRequest withClientSecret:@"fakeclientsecret"];
        
        expect(decodedSignedRequest).willNot.beNil();
    });
});

describe(@"decodeSignedRequest no bad characters", ^{
    it(@"should decode signed request with question mark successfully", ^{
        NSString *signedRequest = @"Ul91Yd6hqcO9RzfPHNelbU4HVoZP8-N7bA8nm3le8vs.W3sic3RhdHVzIjogInNldHRsZWQiLCAicmVmdW5kIjogbnVsbCwgIm1lZGl1bSI6ICJpcGhvbmUiLCAiaWQiOiAiMTc1ODg2MjU5NjIyMTQzNTk2OCIsICJwYXltZW50X2lkIjogODE4Mzc4MTksICJmZWUiOiBudWxsLCAiZGF0ZV9jb21wbGV0ZWQiOiAiMjAxNS0wOC0yNFQxODoyNjowMCIsICJ0YXJnZXQiOiB7InBob25lIjogbnVsbCwgInR5cGUiOiAidXNlciIsICJlbWFpbCI6IG51bGwsICJ1c2VyIjogeyJ1c2VybmFtZSI6ICJkYW5pb2hzIiwgImxhc3RfbmFtZSI6ICJDaGFuIiwgImlzX2ZyaWVuZCI6IGZhbHNlLCAiaXNfZ3JvdXAiOiBmYWxzZSwgImlzX2FjdGl2ZSI6IHRydWUsICJ0cnVzdF9yZXF1ZXN0IjogbnVsbCwgInBob25lIjogbnVsbCwgInByb2ZpbGVfcGljdHVyZV91cmwiOiAiaHR0cHM6Ly9ncmFwaC5mYWNlYm9vay5jb20vdjIuMC8xMDM0MzEwMDE3L3BpY3R1cmU_dHlwZT1zcXVhcmUiLCAiaXNfYmxvY2tlZCI6IGZhbHNlLCAiaWQiOiAiMTQ1MzMwNzExNzY5OTA3MjI4MiIsICJpZGVudGl0eSI6IG51bGwsICJkYXRlX2pvaW5lZCI6ICIyMDE0LTA2LTI5VDA0OjIxOjQ5IiwgImFib3V0IjogIk5vIFNob3J0IEJpbyIsICJkaXNwbGF5X25hbWUiOiAiRGFuaWVsYSBDaGFuIiwgImZyaWVuZHNfY291bnQiOiAxMTEsICJmaXJzdF9uYW1lIjogIkRhbmllbGEiLCAiZnJpZW5kX3JlcXVlc3QiOiBudWxsLCAiZW1haWwiOiBudWxsfX0sICJzdWNjZXNzIjogMSwgImF1ZGllbmNlIjogInByaXZhdGUiLCAiYWN0b3IiOiB7InVzZXJuYW1lIjogImstai13IiwgImxhc3RfbmFtZSI6ICJXb25nIiwgImlzX2ZyaWVuZCI6IGZhbHNlLCAiaXNfZ3JvdXAiOiBmYWxzZSwgImlzX2FjdGl2ZSI6IHRydWUsICJ0cnVzdF9yZXF1ZXN0IjogbnVsbCwgInBob25lIjogbnVsbCwgInByb2ZpbGVfcGljdHVyZV91cmwiOiAiaHR0cHM6Ly92ZW5tb3BpY3MuYXBwc3BvdC5jb20vdS92MS9mLzg2NjgzNzg5LWIxOWUtNDc4ZC1iMzg4LTQ2ZWQ0NDUwY2Q4MCIsICJpc19ibG9ja2VkIjogZmFsc2UsICJpZCI6ICIxMjgyNjY0NTUyMjAyMjQwNDc0IiwgImlkZW50aXR5IjogbnVsbCwgImRhdGVfam9pbmVkIjogIjIwMTMtMTEtMDVUMTc6NDU6MzAiLCAiYWJvdXQiOiAiICIsICJkaXNwbGF5X25hbWUiOiAiS2ltYmVybHkgV29uZyIsICJmcmllbmRzX2NvdW50IjogODcsICJmaXJzdF9uYW1lIjogIktpbWJlcmx5IiwgImZyaWVuZF9yZXF1ZXN0IjogbnVsbCwgImVtYWlsIjogbnVsbH0sICJub3RlIjogInNwbGl0d2lzZSBBcml6b25hIHlvLiBNYWtlIGl0IFx1MjYxNCBcdWQ4M2RcdWRjYjAiLCAiYW1vdW50IjogIjUwLjAyIiwgImFjdGlvbiI6ICJwYXkiLCAiZGF0ZV9jcmVhdGVkIjogIjIwMTUtMDgtMjRUMTg6MjY6MDAiLCAiZGF0ZV9yZW1pbmRlZCI6IG51bGx9XQ";
        NSArray *decodedSignedRequest = [VENRequestDecoder decodeSignedRequest:signedRequest withClientSecret:@"fakeclientsecret"];
        
        expect(decodedSignedRequest).willNot.beNil();
    });
});

SpecEnd
